### ISSUE TITLE
remember me功能

### ISSUE THREAD

**Issue by liuhao0813** [kawhii/sso#24]
#记住我功能
cas.ticket.tgt.rememberMe.enabled = true
cas.ticket.tgt.rememberMe.timeToKillInSeconds = 28800
记住我功能开启，但是不生效问题

**Comment by laomazi2006** [comment]
@liuhao0813 主要实现是客户端的记住，还是cas服务的记住我

**Comment by liuhao0813** [comment]
cas服务器记住我

**Comment by kawhii** [comment]
```properties
cas.ticket.tgt.rememberMe.enabled=true
cas.ticket.tgt.rememberMe.timeToKillInSeconds=20
```
登录后20秒内部访问cas会发现发出一个注销通知，也就是这个问题是不存在的
