### ISSUE TITLE
自定义登录失败多次出现图形校验码

### ISSUE THREAD

**Issue by songxiaoxuan** [kawhii/sso#33]
cas 5.1.4 使用自定义登录认证和和自定义credential的时候怎么做到，当用户连续三次登录失败的时候出现图形校验码或者短信验证码？

**Comment by kawhii** [comment]
首先，这里有两个需求，分别是：
* 自定义credential （可以参考https://github.com/kawhii/sso/tree/master/sso-support/sso-support-custom-auth ，代码已输出，教程尚未落实，正在进行）
* 自定义认证（同上）
* 失败添加校验策略（需要调整flow，在校验失败策略匹配的时候转发到你自己定义的流程，或者输出校验接口信息[这个时候后端必须标志需要验证码否则前端不请求验证信息会有漏洞]，前端收到校验接口信息需要对后端请求校验，校验投放置event，flow先校验，再去到login流程即可）


---

以上说的可能比较抽象，若不理解可以直接联系我，非常欢迎
