### ISSUE TITLE
如何加入验证码验证?

### ISSUE THREAD

**Issue by louisliaoxh1989** [kawhii/sso#37]
如何加入验证码验证?

**Comment by kawhii** [comment]
@louisliaoxh1989 期待新特性发布

**Comment by kawhii** [comment]
@louisliaoxh1989 可以参考一下谷歌验证码那个流程，官网提供了这个支持 https://github.com/apereo/cas/tree/master/support/cas-server-support-captcha

https://apereo.github.io/cas/development/integration/Configuring-Google-reCAPTCHA.html

**Comment by kawhii** [comment]
触发demo主题，并且有系统参数信息才会进行校验

**Comment by kawhii** [comment]
http://blog.csdn.net/u010475041/article/details/78572812
