### ISSUE TITLE
加入自定义认证后，任一用户名可登陆

### ISSUE THREAD

**Issue by louisliaoxh1989** [kawhii/sso#38]
加入自定义认证后，任一用户名可登陆
我去掉了改判断
if ("admin".equals(sysCredential.getUsername())){// && "sso".equals(sysCredential.getSystem())) {

**Comment by kawhii** [comment]
@louisliaoxh1989 当然返回true了允许通过了肯是可以登录，上面只是做一个例子具体业务场景还需调整逻辑
