### ISSUE TITLE
看到blog里面有配置jwt的，没有明白jwt client为什么要注入到cas里面，按照理解jwt无非就是将cas的结果（casRestFormClient）生成token 返回到用户端

### ISSUE THREAD

**Issue by romantictravel** [kawhii/sso#43]
# 关于问题报告

当您有需求或者遇到棘手的问题甚至项目无法启动时，请[打开博客](http://blog.csdn.net/u010475041/article/category/7156505)看是否能找到解决方案

# 提出问题

## 需求
提出需求时请囊括以下要素：

* 业务场景
* 目前使用sso情况
* 是否对外开放
* Cas版本
* 集成客户端SDK(pac4j/cas-client)

## Bug

若是bug问题，请包括以下要素：

* bug出现场景
* 配置文件源码
* Cas版本
* bug紧急情况

**Comment by kawhii** [comment]
你理解的jwt是采用cas的service ticket类型为jwt，而博文的jwt未客户端，两个是不一样的
