### ISSUE TITLE
关于使用Pac4j集成shiro cas,需要过滤一些不需要登录的路径，需要怎么实现

### ISSUE THREAD

**Issue by minlingchao1** [kawhii/sso#45]

**Comment by kawhii** [comment]
1. 采用Pac4j集成shiro是用[buji-pac4j](https://github.com/bujiio/buji-pac4j)
2. 参考以下配置https://github.com/pac4j/buji-pac4j-demo/blob/6c86c96de27eafcac42a42ada2384c2128cbc17a/src/main/resources/shiro.ini#L87

3. 实现`org.pac4j.core.matching.Matcher`接口，返回true时会进行权限并且登录检测，否则放行通过
4. 可以配置`config.authorizers`对权限进行检测，具体需要看业务场景
