### ISSUE TITLE
验证码

### ISSUE THREAD

**Issue by hxj1449** [kawhii/sso#49]
将验证码添加到loginform，会显示图片，但是不会验证，空或者错误，正确。均不会拦截。

**Comment by kawhii** [comment]
debug过了吗？

**Comment by hxj1449** [comment]
有，但是submit得时候没有看到验证码相关的信息啊

**Comment by kawhii** [comment]
在哪个阶段哪个代码里面debug

**Comment by hxj1449** [comment]
sso-config中调试的，然后启动后看的网页的F12

**Comment by kawhii** [comment]
这样看代码看不出的，应该以`build.cmd debug`启动项目采用remote debug方式定位问题
应该在`ValidateLoginCaptchaAction`下定位问题
