### ISSUE TITLE
sso-management 模块启动后访问一直返回404页面

### ISSUE THREAD

**Issue by lynchlee** [kawhii/sso#50]
# 问题
按照博客文章 http://blog.csdn.net/u010475041/article/details/78028658  所描述，直接利用工程里面的代码，编译后启动，弹出浏览器后访问报错,一直没法正常使用sso-management
启动顺序
  sso-config
  sso-server
  sso-management

启动完最后一个模块，弹出浏览器，直接定向到地址 http://passport.sso.com:8443/cas/login?service=http%3A%2F%2Flocalhost%3A8081%2Fmanage.html
  返回的是404页面

直接访问 http://localhost:8081/cas-management 也是返回此404页面

* 环境参数
CAS Version: 5.1.6
CAS Commit Id: d10c36f0e326e911082bebe74d288c1af9b946ae
CAS Build Date/Time: 2017-11-19T14:01:38Z
Spring Boot Version: 1.5.3.RELEASE
------------------------------------------------------------
System Date/Time: 2018-01-05T20:26:00.232
System Temp Directory: /data/apps/opt/tomcat88/temp
------------------------------------------------------------
Java Home: /Library/Java/JavaVirtualMachines/jdk1.8.0_77.jdk/Contents/Home/jre
Java Vendor: Oracle Corporation
Java Version: 1.8.0_77
JCE Installed: no
------------------------------------------------------------
OS Architecture: x86_64
OS Name: Mac OS X
OS Version: 10.12.6
------------------------------------------------------------

求助博主

**Comment by kawhii** [comment]
1. d10c36f0e326e911082bebe74d288c1af9b946ae 并不是本项目的commit id
2. http://blog.csdn.net/u010475041/article/details/78028658 文章中提到的请下载对应工程代码（https://github.com/kawhii/sso/releases/tag/1.4.0）或者更高的版本
