### ISSUE TITLE
[ 登出 ]是否可以修改发送登出时使用的方法

### ISSUE THREAD

**Issue by gogeof** [kawhii/sso#51]
# 关于问题报告

当您有需求或者遇到棘手的问题甚至项目无法启动时，请[打开博客](http://blog.csdn.net/u010475041/article/category/7156505)看是否能找到解决方案

# 提出问题

## 需求
提出需求时请囊括以下要素：

* 业务场景
在使用的过程中，我发现，在配置业务系统的登出url时，默认时通过Post请求发送的，我在想，是否可以修改这个发送的请求方法，比如修改成Get请求
* 目前使用sso情况
正在学习
* 是否对外开放
否
* Cas版本
5.1.6
* 集成客户端SDK(pac4j/cas-client)
pac4j/cas-client

**Comment by kawhii** [comment]
可以的，无论是使用cas-client还是pac4j都可以配置logout，都是采用过滤器处理
