### ISSUE TITLE
不好意思 想请问 您文章的内容

### ISSUE THREAD

**Issue by stereo720712** [kawhii/sso#52]
# 关于问题报告

当您有需求或者遇到棘手的问题甚至项目无法启动时，请[打开博客](http://blog.csdn.net/u010475041/article/category/7156505)看是否能找到解决方案

# 提出问题
http://blog.csdn.net/u010475041/article/details/77893463## 
关于第二篇 helloworld
您写的配置说明 parent pom 并没看到这个文件
整个 cas-server 中 只有一个pom 名称是 sso-server
想请问 那个 parent pom 是怎么配置
需求
提出需求时请囊括以下要素：

* 业务场景
* 目前使用sso情况
* 是否对外开放
* Cas版本
* 集成客户端SDK(pac4j/cas-client)

## Bug

若是bug问题，请包括以下要素：

* bug出现场景
* 配置文件源码
* Cas版本
* bug紧急情况

**Comment by kawhii** [comment]
麻烦到，https://github.com/kawhii/sso/releases/tag/1.0.0 下载源码，包含了第一章所有代码，感谢您的支持
