### ISSUE TITLE
[CAS-5.2.X] [问题] 自定义认证流程

### ISSUE THREAD

**Issue by melodyfff** [kawhii/sso#59]
## Bug
[自定义认证之重写Credential](https://blog.csdn.net/u010475041/article/details/78420322)

- bug出现场景：跳转到自定义登录界面后，进行登录，无法断点到自定义认证流程
- Cas版本：5.2.x

此外我想请问下 CAS-5.2.X 后是否取消了对`deployerConfigContext.xml`配置文件的加载呢？
我自己导入的`deployerConfigContext.xml`没有生效

**Comment by kawhii** [comment]
没有取消该文件的加载，建议用配置java的方式加载

**Comment by melodyfff** [comment]
好的，感谢回复。
此外，我将CAS版本更换到5.2.3后，发现并没有走自定义的流程
if ("admin".equals(sysCredential.getUsername())){// && "sso".equals(sysCredential.getSystem())) {

DEBUG后发现
在5.1.X版本，加载完自定义的流程后，直接正常启动了
```java
    public AbstractCasWebflowConfigurer(FlowBuilderServices flowBuilderServices, FlowDefinitionRegistry loginFlowDefinitionRegistry, ApplicationContext applicationContext, CasConfigurationProperties casProperties) {
        this.flowBuilderServices = flowBuilderServices;
        this.loginFlowDefinitionRegistry = loginFlowDefinitionRegistry;
        this.applicationContext = applicationContext;
        this.casProperties = casProperties;
    }
```
在5.2.X版本加载完自定义流程后，又重新加载了一次（可能是加载默认流程）

所以想请问下，针对您的博客[CAS单点登录-自定义认证之重写Credential](CAS单点登录-自定义认证之重写Credential),在切换到CAS5.2.X版本后，以您的[项目代码](https://github.com/kawhii/sso/releases/tag/1.6.0-RC3)为前提的情况下，自定义的认证流程是否生效呢？
